#pragma once

//comms
#define BUFFER_SIZE 64

#define BAUDRATE 115200

// still gotta define these
#define WHEEL_RADIUS 50
#define CENTER_RADIUS 100
#define REVOLUTION_LENGTH 2*WHEEL_RADIUS*3.14
#define ROTATION_REVOLUTIONS CENTER_RADIUS/WHEEL_RADIUS
#define PI_MUL_PER_STEPSIZE MOTOR_STEPSIZE/(ROTATION_REVOLUTIONS)

// drive settings
#define VEHICLE_X 100
#define VEHICLE_Y 50
#define VEHICLE_STEPS_X VEHICLE_X/REVOLUTION_LENGTH
#define VEHICLE_STEPS_Y VEHICLE_Y/REVOLUTION_LENGTH
#define SAFETY_DISTANCE 5
#define UNITY_DISTANCE 10
#define MAX_TABLE_DISTANCE 100

//pins
#define COLOR_SENSOR_PIN 15

#define TOF_XSHUT_FW_LOW 2
#define TOF_XSHUT_FW_HIGH 3
#define TOF_XSHUT_LEFT 4
#define TOF_XSHUT_RIGHT 5
#define TOF_XSHUT_DOWN 6

#define LEFT_MOTOR_PIN_0 7
#define LEFT_MOTOR_PIN_1 8
#define LEFT_MOTOR_PIN_2 9
#define LEFT_MOTOR_PIN_3 10

#define RIGHT_MOTOR_PIN_0 11
#define RIGHT_MOTOR_PIN_1 12
#define RIGHT_MOTOR_PIN_2 13
#define RIGHT_MOTOR_PIN_3 14


//stepper settings
#define MOTOR_STEPS_PER_REVOLUTION 2048
#define MOTOR_STEPSIZE 5
